"""empty message

Revision ID: efd8e63ebeb0
Revises: 
Create Date: 2025-05-27 09:16:16.435409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd8e63ebeb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proprietario',
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_proprietario')
    )
    op.create_table('veiculo_registrado',
    sa.Column('cod_veiculo', sa.BigInteger(), nullable=False),
    sa.Column('placa', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cod_veiculo')
    )
    op.create_table('banco',
    sa.Column('bnome', sa.String(length=100), nullable=False),
    sa.Column('bendereco', sa.String(), nullable=True),
    sa.Column('id_proprietario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proprietario'], ['proprietario.id_proprietario'], ),
    sa.PrimaryKeyConstraint('bnome')
    )
    op.create_table('caminhao',
    sa.Column('cod_veiculo', sa.BigInteger(), nullable=False),
    sa.Column('marca_caminhao', sa.String(), nullable=True),
    sa.Column('modelo_caminhao', sa.String(), nullable=True),
    sa.Column('capacidade_peso', sa.Float(), nullable=True),
    sa.Column('ano_caminhao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cod_veiculo'], ['veiculo_registrado.cod_veiculo'], ),
    sa.PrimaryKeyConstraint('cod_veiculo')
    )
    op.create_table('carro',
    sa.Column('cod_veiculo', sa.BigInteger(), nullable=False),
    sa.Column('estilo', sa.String(), nullable=True),
    sa.Column('marca_carro', sa.String(), nullable=True),
    sa.Column('modelo_carro', sa.String(), nullable=True),
    sa.Column('ano_carro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cod_veiculo'], ['veiculo_registrado.cod_veiculo'], ),
    sa.PrimaryKeyConstraint('cod_veiculo')
    )
    op.create_table('dono',
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.Column('cod_veiculo', sa.BigInteger(), nullable=False),
    sa.Column('data_compra', sa.Date(), nullable=True),
    sa.Column('alienado_ou_regular', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cod_veiculo'], ['veiculo_registrado.cod_veiculo'], ),
    sa.ForeignKeyConstraint(['id_proprietario'], ['proprietario.id_proprietario'], ),
    sa.PrimaryKeyConstraint('id_proprietario', 'cod_veiculo')
    )
    op.create_table('empresa',
    sa.Column('enome', sa.String(length=100), nullable=False),
    sa.Column('eendereco', sa.String(), nullable=True),
    sa.Column('id_proprietario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proprietario'], ['proprietario.id_proprietario'], ),
    sa.PrimaryKeyConstraint('enome')
    )
    op.create_table('pessoa',
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('num_carteira_motorista', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('id_proprietario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proprietario'], ['proprietario.id_proprietario'], ),
    sa.PrimaryKeyConstraint('cpf')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoa')
    op.drop_table('empresa')
    op.drop_table('dono')
    op.drop_table('carro')
    op.drop_table('caminhao')
    op.drop_table('banco')
    op.drop_table('veiculo_registrado')
    op.drop_table('proprietario')
    # ### end Alembic commands ###
